version: '3'
services:
  binance-parsing:
    build: .
    image: binance-pars
    container_name: container-parsing
    volumes:
      - ./data:/app/data
    command: ["tail", "-f", "/dev/null"]
      

 
      

        

    